#!/command/with-contenv sh
# ←←←← ЭТО ОБЯЗАТЕЛЬНО! Именно этот шебанг и только он!

exec /opt/venv/bin/gunicorn --bind 0.0.0.0:8080 \
                            --workers 1 \
                            --worker-class sync \
                            api:app
